### ISSUE TITLE
Is it possible to add "noteName" ? eg. A2 or C#4

### ISSUE THREAD

**Issue by siddhu09rocks** [mohayonao/mml-emitter#12]
Hi

First of all awesome work !! hats off

Right now we can get noteNumber but I think adding "noteName" would awesome thing 

Let me put this way 

I am using https://stuartmemo.com/qwerty-hancock/ for keyboard as well as mml-emitter for reading out MML.. It would be awesome if we can highlight particular note on keyboard..

each piano key got id with note name such c#4 or b1 etc. so if you can return noteName it would be great feature 

Think about it

**Comment by mohayonao** [comment]
Thanks!

I think that this module should provide a minimum information to play music. It is not include note names that are same information as note number.

So, please use this function to convert.

```js
function noteNumberToNoteName(n) {
  return [
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"
  ][n % 12] + (Math.floor(n / 12) - 2);
}

console.log(noteNumberToNoteName(60));  // → "C3"
console.log(noteNumberToNoteName(127)); // → "G8"
```

**Comment by siddhu09rocks** [comment]
Hey Thanks a lot for getting back ..and trying to help me out .. Appreciated !!

that function does return NoteName but with some error I guess

check this out..

![mml](https://cloud.githubusercontent.com/assets/24547336/21587233/e8018e2e-d0ff-11e6-870a-a1440f82b8b8.jpg)

**Comment by mohayonao** [comment]
In MML, `C4`'s 4 means a quarter note, not means octave 4.

```
C4
||
|Note Length
Note Name
```

You can specify an octave with `o` command.

```
o1 b
o4 c
o1 c+
```

**Comment by siddhu09rocks** [comment]
Oh is that so ? My bad. I am pretty much newbie 
Thanks a lot for helping out .. Appreciated !!
